/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LuyenTapXeMay;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Admin
 */
public class XeMayForm extends javax.swing.JFrame {

    private DefaultTableModel defaultTableModel;
    private XeMayS serr;

    /**
     * Creates new form XeMay
     */
    public XeMayForm() {
        initComponents();
        this.serr = new XeMayS();
        this.loadTale();
    }

    public void loadTale() {
        defaultTableModel = new DefaultTableModel();
        defaultTableModel = (DefaultTableModel) tbXemay.getModel();
        defaultTableModel.setRowCount(0);
        for (XeMay xx : this.serr.getList()) {
            defaultTableModel.addRow(new Object[]{
                xx.getId(), xx.getMa(), xx.getTen(), String.format("%.2f", xx.getGianhap()), String.format("%.2f", xx.getGiaban()), xx.getSoluong()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtGianhap = new javax.swing.JTextField();
        txtGiaBan = new javax.swing.JTextField();
        txtSo = new javax.swing.JTextField();
        txtTen = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        cbLoaiXe = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbXemay = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID:");

        lblId.setText("_");

        jLabel3.setText("Ma xe:");

        txtMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaActionPerformed(evt);
            }
        });

        jLabel4.setText("Ten:");

        jLabel5.setText("Gia nhap:");

        jLabel6.setText("Gia ban:");

        jLabel7.setText("So luong:");

        btnThem.setText("Them");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sua");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xoa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        cbLoaiXe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Xe máy điện", "Xe Số", "Xe Tay Ga", "Xe Điện" }));
        cbLoaiXe.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbLoaiXeItemStateChanged(evt);
            }
        });

        jLabel8.setText("Loai xe:");

        tbXemay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "ma", "Ten", "gianhap", "Gia ban", "so luong"
            }
        ));
        tbXemay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbXemayMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbXemay);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(88, 88, 88)
                                .addComponent(jLabel5))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtTen, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                    .addComponent(txtMa))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtGiaBan)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbLoaiXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtGianhap)
                            .addComponent(txtSo)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnThem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSua)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnClear)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblId)
                    .addComponent(jLabel5)
                    .addComponent(txtGianhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbLoaiXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtSo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnXoa)
                    .addComponent(btnClear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public XeMay getForm() {
        String id = lblId.getText().trim();
        String ten = txtTen.getText().trim();
        String ma = txtMa.getText().trim();
        String gianhap = txtGianhap.getText().trim();
        String giaban = txtGiaBan.getText().trim();
        String so = txtSo.getText().trim();
//        int idh = id.equals("_") ? 0 : Integer.parseInt(id);
        int sok = -1;
        try {
            sok = Integer.parseInt(so);
            if (sok <= 0) {
                JOptionPane.showMessageDialog(this, "nhap <0");
                return null;
            }
        } catch (NumberFormatException numberFormatException) {
            numberFormatException.printStackTrace();
            return null;
        }
        if (ten.length() == 0
                || ma.length() == 0
                || gianhap.length() == 0
                || giaban.length() == 0 || so.length() == 0) {
            JOptionPane.showMessageDialog(this, "khong de tronf");
            return null;
        }
        double nhap = 0;
        double ban = 0;
        try {
            nhap = Double.parseDouble(gianhap);
            if (nhap < 0) {
                JOptionPane.showMessageDialog(this, "Khong <0");
                return null;
            }
        } catch (NumberFormatException numberFormatException) {
            numberFormatException.printStackTrace();
            return null;
        }
        try {
            ban = Double.parseDouble(giaban);
            if (ban < 0) {
                JOptionPane.showMessageDialog(this, "Khong <0");
                return null;
            }
        } catch (NumberFormatException numberFormatException) {
            numberFormatException.printStackTrace();
            return null;
        }
        XeMay xxx = new XeMay(id, ma, ten, nhap, ban, sok);
        return xxx;
    }

    private void txtMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearForrm();
    }//GEN-LAST:event_btnClearActionPerformed

    public void clearForrm() {
        // TODO add your handling code here:
        lblId.setText("_");
        txtGiaBan.setText("");
        txtGianhap.setText("");
        txtMa.setText("");
        txtTen.setText("");
        txtSo.setText("");
    }

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int row = tbXemay.getSelectedRow();
        if (row == -1) {
            return;
        }
        int choice = JOptionPane.showConfirmDialog(this, "Xac nhan xoa");
        if (choice != JOptionPane.YES_OPTION) {
            return;
        }
        String ma = tbXemay.getValueAt(row, 1).toString();
        this.serr.delete(ma);
        this.loadTale();
        this.clearForrm();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        int row = tbXemay.getSelectedRow();
        if (row == -1) {
            return;
        }
        XeMay xmm = this.getForm();
        if (xmm == null) {
            return;
        }
//        String ma=tbXemay.getValueAt(row, 1).toString();
        this.serr.update(xmm.getMa(), xmm);
        this.loadTale();
        this.clearForrm();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        if (ckeckma()) {
            return;
        }
        XeMay xmm = this.getForm();
        if (xmm == null) {
            return;
        }
        this.serr.insert(xmm);
        this.loadTale();
        this.clearForrm();
    }//GEN-LAST:event_btnThemActionPerformed

    public boolean ckeckma() {
        // TODO add your handling code here:
        for (XeMay oj : this.serr.getList()) {
            if (oj.getMa().equals(txtMa.getText().trim())) {
                return true;
            }
        }
        return false;
    }

    private void tbXemayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbXemayMouseClicked
        // TODO add your handling code here:
        int row = tbXemay.getSelectedRow();
        lblId.setText(tbXemay.getValueAt(row, 0).toString());
        txtMa.setText(tbXemay.getValueAt(row, 1).toString());
        txtTen.setText(tbXemay.getValueAt(row, 2).toString());
        txtGianhap.setText(tbXemay.getValueAt(row, 3).toString());
        txtGiaBan.setText(tbXemay.getValueAt(row, 4).toString());
        txtSo.setText(tbXemay.getValueAt(row, 5).toString());
    }//GEN-LAST:event_tbXemayMouseClicked

    private void cbLoaiXeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbLoaiXeItemStateChanged
        // TODO add your handling code here:
        String loaiXe = cbLoaiXe.getSelectedItem().toString();
        defaultTableModel.setRowCount(0);
        ArrayList<XeMay> list = serr.getLoaiXE(loaiXe);
        if (list.isEmpty()) {
            return;
        }
        for (XeMay x : list) {
            defaultTableModel.addRow(new Object[]{x.getId(), x.getMa(), x.getTen(), x.getGianhap(), x.getGiaban(), x.getSoluong()});
        }
    }//GEN-LAST:event_cbLoaiXeItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(XeMayForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(XeMayForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(XeMayForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(XeMayForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new XeMayForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbLoaiXe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblId;
    private javax.swing.JTable tbXemay;
    private javax.swing.JTextField txtGiaBan;
    private javax.swing.JTextField txtGianhap;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtSo;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables
}
