/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NhanVienHH;

import services.NhanVienSer;
import java.sql.Date;
import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import javax.swing.ButtonGroup;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.ChucVu;
import models.CuaHang;
import models.NhanVien;
import services.ChucVuSer;
import services.CuaHangService;
import services.impls.IChucVuSer;
import services.impls.ICuaHangSer;

/**
 *
 * @author Admin
 */
public class NhanVienForm extends javax.swing.JFrame {

    private DefaultTableModel defaultTableModel;
    private DefaultComboBoxModel defaultComboBoxModel;
    private NhanVienSer serr;
    private ICuaHangSer chS;
    private IChucVuSer serCV;
    private ButtonGroup bg;

    /**
     * Creates new form NhanVien
     */
    public NhanVienForm() {
        initComponents();
        this.serr = new NhanVienSer();
        this.chS = new CuaHangService();
        this.serCV = new ChucVuSer();
        rdgt();
        this.loadComBoCH();
//        this.loadComBoCV();

        this.loadTable();
    }

    public void rdgt() {
        bg = new ButtonGroup();
        bg.add(rdNu);
        bg.add(rdNam);
    }

    public void loadTable() {
        defaultTableModel = new DefaultTableModel();
        defaultTableModel = (DefaultTableModel) tb_NhanVien.getModel();
        defaultTableModel.setRowCount(0);
        for (NhanVien nv : this.serr.getLisst()) {
            defaultTableModel.addRow(new Object[]{
                nv.getId(), nv.getManv(), nv.getHonv(), nv.getTenDem(), nv.getTennv(), nv.getGt(), nv.getNgaySinh(), nv.getDiachi(), nv.getSdt(), nv.getMatkhau(), nv.getCuaHang(), nv.getChucVu().getTen(), nv.getTrangThai() == 0 ? "Hoạt động" : "Không hoạt động"
            });
        }
    }

    public void loadComBoCH() {
        defaultComboBoxModel = new DefaultComboBoxModel<>();
        defaultComboBoxModel = (DefaultComboBoxModel) cbCuaHabg.getModel();
        List<CuaHang> listCH = this.chS.getList();

        for (CuaHang c : listCH) {

            defaultComboBoxModel.addElement(c);
        }

    }

//    public void loadComBoCV() {
//        defaultComboBoxModel=new DefaultComboBoxModel<>();
//        defaultComboBoxModel = (DefaultComboBoxModel) cbChucVu.getModel();
//       
//         List<ChucVu> listCV= this.serCV.getList();
//      int i;
//        for ( i = 0; i < listCV.size(); i++) {
//           String ten=this.serCV.getList().get(i).getTen();
////         for (Object o : new HashSet<li> ) {
////            ChucVu cv=
////        } 
//        }
//}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txt_ho = new javax.swing.JTextField();
        txtns = new javax.swing.JTextField();
        txt_Ma = new javax.swing.JTextField();
        txt_ten = new javax.swing.JTextField();
        txt_tenDem = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtdc = new javax.swing.JTextField();
        rdNam = new javax.swing.JRadioButton();
        rdNu = new javax.swing.JRadioButton();
        txt_mk = new javax.swing.JTextField();
        cb_trangthai = new javax.swing.JComboBox<>();
        txtsdt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_NhanVien = new javax.swing.JTable();
        btnNew = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cbCuaHabg = new javax.swing.JComboBox<CuaHang>();
        txtTenCV = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Id");

        jLabel2.setText("Mã");

        jLabel3.setText("Tên");

        jLabel4.setText("Tên Đệm");

        jLabel5.setText("Họ Tên");

        jLabel6.setText("Giới Tính");

        jLabel7.setText("Ngày sinh");

        jLabel8.setText("Địa chỉ");

        jLabel9.setText("Mật khẩu");

        jLabel10.setText("Trạng thái");

        jLabel11.setText("Sdt");

        rdNam.setText("Nam");

        rdNu.setText("Nữ");

        cb_trangthai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hoạt động", "Không hoạt động" }));

        tb_NhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Mã", "Họ NV", "Tên Đệm NV", "Tên NV", "Giới tính", "Ngày sinh", "Địa chỉ", "Sđt", "Mật khẩu", "Tên cửa hàng", "Chức vụ", "Trạng Thái"
            }
        ));
        tb_NhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_NhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_NhanVien);

        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/applications/plus.png"))); // NOI18N
        btnNew.setText("New");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/applications/floppy-disk.png"))); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/applications/pencil.png"))); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/applications/remove.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 204));
        jLabel12.setText("Nhân Viên");

        jLabel13.setText("Chức vụ");

        jLabel14.setText("Tên Cửa Hàng");

        cbCuaHabg.setModel(new javax.swing.DefaultComboBoxModel<CuaHang>());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNew)
                                .addGap(29, 29, 29)
                                .addComponent(btnSave)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnUpdate)
                                .addGap(18, 18, 18)
                                .addComponent(btnDelete)
                                .addGap(23, 23, 23))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbCuaHabg, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txt_id, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_Ma, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_ten, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_tenDem, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_mk, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cb_trangthai, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtTenCV, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(65, 65, 65)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel7)
                                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtns)
                                                    .addComponent(txtdc)
                                                    .addComponent(txtsdt)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel6)
                                                    .addComponent(jLabel5))
                                                .addGap(25, 25, 25)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(rdNam)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(rdNu)
                                                        .addGap(0, 0, Short.MAX_VALUE))
                                                    .addComponent(txt_ho)))))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(254, 254, 254))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel12)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(txt_Ma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdNam)
                    .addComponent(rdNu, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(txtns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(txt_tenDem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(txt_mk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(cbCuaHabg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtTenCV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cb_trangthai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNew)
                    .addComponent(btnSave)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 public void clearForm() {
        // TODO add your handling code here:
        this.txt_id.setText("");
        this.txt_Ma.setText("");
        this.txt_ten.setText("");
        this.txt_tenDem.setText("");
        this.txt_ho.setText("");
        this.txtns.setText("");
        this.txtdc.setText("");
        this.txtsdt.setText("");
        this.txt_mk.setText("");
        rdNam.isSelected();
        this.cbCuaHabg.setSelectedIndex(0);
        this.txtTenCV.setText("");
        cb_trangthai.setSelectedIndex(0);
    }

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
        this.clearForm();
    }//GEN-LAST:event_btnNewActionPerformed
    public NhanVien getFormData() {
        String id = txt_id.getText().trim();
        String ma = txt_Ma.getText().trim();
        String ten = txt_ten.getText().trim();
        String tendem = txt_tenDem.getText().trim();
        String ho = txt_ho.getText().trim();
//        Date ngay = Date.valueOf(txtns.getText());
//        SimpleDateFormat ff=new SimpleDateFormat("dd/MM/yyyy");
//        ff.format(ngay);
        String ngay = txtns.getText().trim();

        String tenCV = txtTenCV.getText().trim();
        ChucVu cv = new ChucVu();
        cv.setTen(tenCV);
        CuaHang tenCH = (CuaHang) cbCuaHabg.getSelectedItem();
//        ChucVu cv = (ChucVu) cbChucVu.getSelectedItem();
        String sdt = txtsdt.getText().trim();

        String dc = txtdc.getText().trim();
        String gt = rdNam.isSelected() ? "Nam" : "Nữ";
        String mk = txt_mk.getText().trim();
        int tt = cb_trangthai.getSelectedIndex();
        if (ma.length() == 0
                || ten.length() == 0
                || tendem.length() == 0
                || ho.length() == 0
                || tenCV.length() == 0
                || sdt.length() == 0
                || dc.length() == 0
                || mk.length() == 0) {
            JOptionPane.showMessageDialog(this, "không để trống");
            return null;

        }
        String REG = "^0[0-9]{9}";
        if (!sdt.matches(REG)) {
            JOptionPane.showMessageDialog(this, "Sai dinh dang Sdt. Nhap lai Sdt !");
            return null;
        }
        Date date = null;
        try {
            date = Date.valueOf(ngay);

        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(this, "nhập lại ngày");
            return null;
        }
        NhanVien nhanVien = new NhanVien(id, ma, ho, tendem, ten, gt, date, dc, sdt, mk, tenCH, cv, tt);
        return nhanVien;
    }

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String chk = this.serr.checkManv(txt_Ma.getText());
        if (chk != null) {
            JOptionPane.showMessageDialog(this, "Trùng mã ");
            return;
        }
        NhanVien nvv = this.getFormData();
        if (nvv == null) {
            return;
        }
        this.serr.inssertnv(nvv);
        JOptionPane.showMessageDialog(this, "thêm thành công");
        this.loadTable();
        this.clearForm();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        int row = tb_NhanVien.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "chọn dòng để sửa");

            return;
        }
        String chk = this.serr.checkManv(txt_Ma.getText());
        if (chk == null) {
            JOptionPane.showMessageDialog(this, "không tồn tại mã không thể sửa ");
            return;
        }
        NhanVien nvvv = this.getFormData();
        if (nvvv == null) {
            return;
        }

        this.serr.updatenv(nvvv.getManv(), nvvv);
        this.loadTable();
        JOptionPane.showMessageDialog(this, "Sửa thành công");
        this.clearForm();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int row = tb_NhanVien.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "chọn dòng để xoá");

            return;
        }
        int choice = JOptionPane.showConfirmDialog(this, "Xac nhan xoa?");
        if (choice != JOptionPane.YES_OPTION) {
            return;
        }
        String ma = tb_NhanVien.getValueAt(row, 1).toString();
        this.serr.deletenv(ma);
        this.loadTable();
        this.clearForm();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tb_NhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_NhanVienMouseClicked
        // TODO add your handling code here:
        int row = tb_NhanVien.getSelectedRow();
        txt_id.setText(tb_NhanVien.getValueAt(row, 0).toString());
        txt_Ma.setText(tb_NhanVien.getValueAt(row, 1).toString());
        txt_ten.setText(tb_NhanVien.getValueAt(row, 4).toString());
        txt_tenDem.setText(tb_NhanVien.getValueAt(row, 3).toString());
        txt_ho.setText(tb_NhanVien.getValueAt(row, 2).toString());
        if (tb_NhanVien.getValueAt(row, 5).toString().equals("Nam")) {
            rdNam.setSelected(true);
        } else {
            rdNu.setSelected(true);
        }
        txtns.setText(tb_NhanVien.getValueAt(row, 6).toString());
        txtdc.setText(tb_NhanVien.getValueAt(row, 7).toString());
        txtsdt.setText(tb_NhanVien.getValueAt(row, 8).toString());
        txt_mk.setText(tb_NhanVien.getValueAt(row, 9).toString());
//        cbCuaHabg.setSelectedItem(tb_NhanVien.getValueAt(row, 10).toString());

        CuaHang cuaH = (CuaHang) tb_NhanVien.getValueAt(row, 10);
        int slCH = cbCuaHabg.getItemCount();
        for (int i = 0; i < slCH; i++) {
            CuaHang cua = cbCuaHabg.getItemAt(i);
            if (cua.getTen().equals(cuaH.getTen())) {
                cbCuaHabg.setSelectedIndex(i);
            }
        }
//        ChucVu chucV = (ChucVu) tb_NhanVien.getValueAt(row, 11);
//        for (int i = 0; i < cbChucVu.getItemCount(); i++) {
//            ChucVu cvu = cbChucVu.getItemAt(i);
//            if (cvu.getTen().equals(chucV.getTen())) {
//                cbChucVu.setSelectedIndex(i);
//            }
//        }
        txtTenCV.setText(tb_NhanVien.getValueAt(row, 11).toString());
        cb_trangthai.setSelectedItem(tb_NhanVien.getValueAt(row, 12).toString());
    }//GEN-LAST:event_tb_NhanVienMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhanVienForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhanVienForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhanVienForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhanVienForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NhanVienForm nvF = new NhanVienForm();
                nvF.setLocationRelativeTo(null);
                nvF.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<CuaHang> cbCuaHabg;
    private javax.swing.JComboBox<String> cb_trangthai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdNam;
    private javax.swing.JRadioButton rdNu;
    private javax.swing.JTable tb_NhanVien;
    private javax.swing.JTextField txtTenCV;
    private javax.swing.JTextField txt_Ma;
    private javax.swing.JTextField txt_ho;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_mk;
    private javax.swing.JTextField txt_ten;
    private javax.swing.JTextField txt_tenDem;
    private javax.swing.JTextField txtdc;
    private javax.swing.JTextField txtns;
    private javax.swing.JTextField txtsdt;
    // End of variables declaration//GEN-END:variables
}
